algorithm: cocoa
save_dir: ./saved_models/classic_cv
save_name: cocoa_imagenet_100k_0
resume: True
load_path: ./saved_models/classic_cv/cocoa_imagenet_100k_0/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 1024
num_train_iter: 1048576
num_eval_iter: 5120
num_labels: 100000
batch_size: 64
eval_batch_size: 256
hard_label: True
thresh_warmup: True
p_cutoff: 0.8
ulb_loss_ratio: 1.0
uratio: 7
T: 0.5
dist_align: True
contrastive_T: 0.1
proj_size: 128
ema_m: 0.999
ema_p: 0.999
crop_ratio: 0.875
img_size: 224
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.001
amp: False
clip: 0.0
use_cat: False
net: resnet50
net_from_name: False
data_dir: /home/
dataset: imagenet
train_sampler: RandomSampler
num_classes: 810
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10004
dist_backend: nccl
gpu: None
use_pretrain: False
