algorithm: comatch
save_dir: ./saved_models/classic_cv_imb
save_name: comatch_abc_cifar10_lb1500_150_ulb3000_150_0
resume: True
load_path: ./saved_models/classic_cv_imb/comatch_abc_cifar10_lb1500_150_ulb3000_150_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 256
num_train_iter: 262144
num_eval_iter: 1024
num_log_iter: 256
num_labels: 1500
batch_size: 64
eval_batch_size: 256
contrast_p_cutoff: 0.8
contrast_loss_ratio: 1.0
ulb_loss_ratio: 1.0
proj_size: 128
queue_batch: 5
smoothing_alpha: 0.9
uratio: 2
T: 0.2
da_len: 32
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_28_2
net_from_name: False
use_epass: True
data_dir: /home/data
dataset: cifar10
train_sampler: RandomSampler
num_classes: 10
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10183
dist_backend: nccl
gpu: None
include_lb_to_ulb: False
lb_imb_ratio: 150
ulb_imb_ratio: 150
ulb_num_labels: 3000
imb_algorithm: abc
abc_p_cutoff: 0.95
abc_loss_ratio: 1.0
